# Introduction of the Linear Algebra Package in Python

In this tutorial, I will introduce two packages, numpy and scipy (in particular scipy.linalg), that could be useful for scientific and numerical computations. The link for the scipy documentation is https://docs.scipy.org/doc/scipy-1.4.1/reference/ and you could find some scipy lecture notes at http://scipy-lectures.org/. As for the numpy package, you may take a look at https://numpy.org/.

The scipy package has many submodules covering a lot of topics such as integration, optimization, statistics and linear algebra. In this tutorial, we will focus only on linear algebra submodule scipy.linalg. In addition, we will be using some features of numpy package since that is how we will be representing matrices. 

I will give some quick intro covering some of the tools that we use in scipy.linalg and numpy so that this tutorial is self-contained. For more information on scipy.linalg, please visit https://docs.scipy.org/doc/scipy/reference/linalg.html

As an example of how we could use Python, we will be covering coordinate vector $[x]_{\mathfrak B}$ of a given vector $x$ with respect to a given basis ${\mathfrak B}$. In addition, a definition for the ${\mathfrak B}$-matrix of a given linear transformation $T$ will also be covered.

If you ever need to install these packages on your computer, you could use the following codes:

!{sys.executable} -m pip install numpy

!{sys.executable} -m pip install scipy

In [1]:
import numpy as np
import scipy.linalg as la

#We first define 2x2 matrices A and B. Here, note that [1,1] is the first row while [2,3] is the second row of matrix A.
A=np.array([[1,1],[2,3]])
B=np.array([[-2,1],[3,-1]])

#In a similar way, we could define vectors v and w:
v=[5,10]
w=[-2,4]

print(A)
print(type(A))


[[1 1]
 [2 3]]
<class 'numpy.ndarray'>


In [2]:
#Alternatively, we could define matrices as
A1=np.matrix([[1,1],[2,3]])

print(A1)
print('Type of A1 is {}'.format(type(A1)))

[[1 1]
 [2 3]]
Type of A1 is <class 'numpy.matrix'>


In [3]:
#We can use np.dot() for dot product of vectors:
np.dot(v,w)

30

In [4]:
# We can also use np.dot() for matrix-matrix multiplication and matrix-vector multiplication:

print(np.dot(A,v))
print('-------------')
print(np.dot(A,B))


[15 40]
-------------
[[ 1  0]
 [ 5 -1]]


Let's see what we can do with the linalg submodule:

In [5]:
#We can compute inverses:
la.inv(A)

array([[ 3., -1.],
       [-2.,  1.]])

In [6]:
#We can use it to solve systems of equations given as Ax=w:
la.solve(A,w)

array([-10.,   8.])

## Example 1: Finding the coordinate vector of a given vector

In this example, we would like to find coordinate vector $[x]_{\mathfrak B}$ of a given vector $x$ with respect to a basis ${\mathfrak B}$ containing vectors $v_1,v_2$ and $v_3$ as defined below.

In [7]:
#First, let's define vectors in the bases B={v_1,v_2,v_3}:
v_1=np.array([1,2,3])
v_2=np.array([1,-1,4])
v_3=np.array([1,0,2])

#and the vector x:
x=np.array([4,2,-1])

x

array([ 4,  2, -1])

To find the coordinate vector, we first have to write $x$ as a linear combination of $v_1,v_2$ and $v_3$ as

$x=c_1v_1+c_2v_2+c_2v_3$

This means that, we will be solving the system $Ac=x$ where $A$ is the matrix with columns $v_1,v_2$ and $v_3$. So, we need to write $A$ first.

In [8]:
A1=np.array([v_1,v_2,v_3])

A1

array([[ 1,  2,  3],
       [ 1, -1,  4],
       [ 1,  0,  2]])

Notice that if we write in this way, we will create a matrix with rows $v_1, v_2$ and $v_3$ instead of columns. To fix this, we will need to switch roles of rows and columns. We can do that by taking the $\it transpose$ of matrix A.

In [9]:
A=np.transpose(A1)

A

array([[ 1,  1,  1],
       [ 2, -1,  0],
       [ 3,  4,  2]])

Now, we can solve the system $Ac=x$ by using la.solve().

In [10]:
la.solve(A,x)

array([-1., -4.,  9.])

This is in fact our coordinate vector since it encodes coefficients of $v_1, v_2$ and $v_3$ in the linear combination. Let's check our work:

In [11]:
linear_combination=(-1)*v_1+(-4)*v_2+(9)*v_3

linear_combination, x

(array([ 4,  2, -1]), array([ 4,  2, -1]))

In [12]:
#We could also use a truth statement for this:

linear_combination==x

array([ True,  True,  True])

## Define a function

Now, we know how to find the coordinate vector of a given vector with respect to any given basis. Let's collect all our work and write a function finding coordinates for any given basis. 

In [13]:
def coordinate_vector(basis,x):
    A0=np.array(basis)
    A=np.transpose(A0)
    return la.solve(A,x)

We should check if this definition is working well by using the example that we did above:

In [14]:
B=[v_1,v_2,v_3]
coordinate_vector(B,x)

array([-1., -4.,  9.])

This is the same vector as before. So, the definition is working well. 

Alternatively, we could create another function to check our work. We first #define the coordinate vector, then set the initial linear combination to 0 so that we could use it later. Note that we should be adding terms one by one as follows since the basis list might change from problem to problem. 

In [15]:
def check_coordinate_function(basis,x):
    coor=coordinate_vector(basis,x)       
    lin_combination=0                   
    for i in range(0,len(basis)):         
        lin_combination +=coor[i]*basis[i] 
    return print('Linear combination result is {} while the original vector x is {}.'.format(lin_combination,x))
    
check_coordinate_function(B,x)
    

Linear combination result is [ 4.  2. -1.] while the original vector x is [ 4  2 -1].


## Example 2

Let's solve another problem with more basis vectors and see how simple it becomes when we use the definitions above.

In [16]:
v_1=np.array([1,2,3,4,5])
v_2=np.array([1,-1,4,2,2])
v_3=np.array([1,0,2,2,2])
v_4=np.array([1,0,1,-1,2])
v_5=np.array([1,0,2,0,0])

#and the vector x:
x_2=np.array([4,2,-1,1,1])

B_2=[v_1,v_2,v_3,v_4,v_5]

B_2

[array([1, 2, 3, 4, 5]),
 array([ 1, -1,  4,  2,  2]),
 array([1, 0, 2, 2, 2]),
 array([ 1,  0,  1, -1,  2]),
 array([1, 0, 2, 0, 0])]

In [17]:
coordinate_vector(B_2,x_2)

array([-0.9375 , -3.875  ,  6.40625,  0.3125 ,  2.09375])

In [18]:
check_coordinate_function(B_2,x_2)

Linear combination result is [ 4.  2. -1.  1.  1.] while the original vector x is [ 4  2 -1  1  1].


## $\mathfrak B$-matrix of a linear transformation

Now, let's see how we could write the matrix of a given linear transformation with respect to a given basis $\mathfrak B=\{v_1,v_2,\ldots,v_n\}$. 

Recall that a transformation $T:{\mathbb R}^n\to{\mathbb R}^n$ is called a linear transformation if there is an $n\times n$ matrix $A$ such that $T(x)=Ax$ for any vector $x$ in ${\mathbb R}^n$. 

The $\mathfrak B$-matrix of $T$ is the matrix $B$ that takes coordinate vector $[x]_{\mathfrak B}$ to $[T(x)]_{\mathfrak B}$. That is, $[T(x)]_{\mathfrak B}=B[x]_{\mathfrak B}$ for all $x$ in ${\mathbb R}^n$. 

Let $S$ be the matrix whose columns are the basis vectors in $\mathfrak B$. Thus, we have $x=S[x]_{\mathfrak B}$. In class, we showed that $B=S^{-1}AS$. This is the easiest and shortest way of writing a code for the ${\mathfrak B}$ matrix of $T$, as given below.


In [19]:
def B_matrix(basis, A):
    B0=np.array(basis)
    S=np.transpose(B0)
    S_inv=la.inv(S)
    mid=np.dot(A,S)
    B=np.dot(S_inv,mid)
    return B

### Example

Consider the linear transformation $T:{\mathbb R}^n\to {\mathbb R}^n$ such that
$T(x)=Ax$ where A=$\begin{bmatrix}4 & 1\\3 & 2\end{bmatrix}$ and 
${\mathfrak B}=\{\begin{bmatrix}-3\\ 2\end{bmatrix},\begin{bmatrix}2\\-1\end{bmatrix}\}$ is the given basis. Find the ${\mathfrak B}$-matrix of the linear transformation $T$.

In [20]:
B=(np.array([-3,2]),np.array([2,-1])) #basis
A=np.array([[4,1],[3,2]]) #matrix A

B_matrix(B,A)

array([[-20.,  15.],
       [-35.,  26.]])

As the quarter progress, we will explore more topics such as determinants, orthogonalization and eigenvalue-eigenvectors. 